spring:
  config:
    import: optional:classpath:application-secret.yml
  application:
    name: pleegie

  datasource:
    url: jdbc:mysql://localhost:3306/pleegie?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

  # properties include secret file
  profiles:
    include: secret

uploadPath: c:/upload/

ai:
  python-server-url: http://localhost:8000/

logging:
  level:
    market_it.pleegie: DEBUG